export const STATE_NAMES = {
  AL: 'Alabama',
  AK: 'Alaska',
  AZ: 'Arizona',
  AR: 'Arkansas',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  FL: 'Florida',
  GA: 'Georgia',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VT: 'Vermont',
  VA: 'Virginia',
  WA: 'Washington',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming',
  DC: 'District of Columbia',
  Federal: 'Federal (FOIA)',
}

export const STATE_LAW_NAMES = {
  AL: 'Alabama Open Records Act',
  AK: 'Alaska Public Records Act',
  AZ: 'Arizona Public Records Law',
  AR: 'Arkansas Freedom of Information Act',
  CA: 'California Public Records Act',
  CO: 'Colorado Open Records Act',
  CT: 'Connecticut Freedom of Information Act',
  DE: 'Delaware Freedom of Information Act',
  FL: 'Florida Public Records Law',
  GA: 'Georgia Open Records Act',
  HI: 'Hawaii Uniform Information Practices Act',
  ID: 'Idaho Public Records Act',
  IL: 'Illinois Freedom of Information Act',
  IN: 'Indiana Access to Public Records Act',
  IA: 'Iowa Open Records Act',
  KS: 'Kansas Open Records Act',
  KY: 'Kentucky Open Records Act',
  LA: 'Louisiana Public Records Law',
  ME: 'Maine Freedom of Access Act',
  MD: 'Maryland Public Information Act',
  MA: 'Massachusetts Public Records Law',
  MI: 'Michigan Freedom of Information Act',
  MN: 'Minnesota Government Data Practices Act',
  MS: 'Mississippi Public Records Act',
  MO: 'Missouri Sunshine Law',
  MT: 'Montana Right to Know',
  NE: 'Nebraska Public Records Statutes',
  NV: 'Nevada Public Records Act',
  NH: 'New Hampshire Right-to-Know Law',
  NJ: 'New Jersey Open Public Records Act',
  NM: 'New Mexico Inspection of Public Records Act',
  NY: 'New York Freedom of Information Law',
  NC: 'North Carolina Public Records Law',
  ND: 'North Dakota Open Records Law',
  OH: 'Ohio Public Records Act',
  OK: 'Oklahoma Open Records Act',
  OR: 'Oregon Public Records Law',
  PA: 'Pennsylvania Right-to-Know Law',
  RI: 'Rhode Island Access to Public Records Act',
  SC: 'South Carolina Freedom of Information Act',
  SD: 'South Dakota Open Records Law',
  TN: 'Tennessee Public Records Act',
  TX: 'Texas Public Information Act',
  UT: 'Utah Government Records Access and Management Act',
  VT: 'Vermont Public Records Act',
  VA: 'Virginia Freedom of Information Act',
  WA: 'Washington Public Records Act',
  WV: 'West Virginia Freedom of Information Act',
  WI: 'Wisconsin Open Records Law',
  WY: 'Wyoming Public Records Act',
  DC: 'DC Freedom of Information Act',
  Federal: 'Freedom of Information Act (FOIA)',
}

export function getStateName(code) {
  return STATE_NAMES[code] || code
}

export function getLawName(code) {
  return STATE_LAW_NAMES[code] || `${getStateName(code)} Public Records Law`
}

export const ALL_JURISDICTIONS = Object.keys(STATE_NAMES)
